"""setup.py, run from a sandbox's copy with --quiet, as a sync runs it.

The tests run in order and share the sandbox, so each one starts from where the one before it
left off, and puts back what it changed. test_setup_questions.py covers what needs a person.
"""

import json
import re
import shutil
import stat
import sys
import threading
import time
from collections.abc import Iterator
from dataclasses import dataclass
from pathlib import Path

import pytest

from helpers import (
    Run,
    Sandbox,
    git,
    link_target,
    make_junction,
    new_sandbox,
    remove_link,
    remove_sandbox,
    run_command,
    run_python,
    shared_module,
    write_text,
)

pytestmark = pytest.mark.xdist_group("setup")

MARKER = "<!-- Generated by dev-home-tools setup from "


@dataclass(frozen=True)
class First:
    """The sandbox, its first setup run, and what its root held before that run."""

    box: Sandbox
    run: Run
    root_before: set[str]


@pytest.fixture(scope="module")
def first(request: pytest.FixtureRequest) -> Iterator[First]:
    box = new_sandbox("setup")
    failed = request.session.testsfailed
    root_before = {entry.name for entry in box.tools.iterdir()}
    yield First(box, setup(box), root_before)
    if request.session.testsfailed > failed:
        print(f"Sandbox kept: {box.root}")
    else:
        remove_sandbox(box)


@pytest.fixture(scope="module")
def box(first: First) -> Sandbox:
    return first.box


def setup(box: Sandbox, *args: str, env: dict[str, str | None] | None = None) -> Run:
    return run_python(box, "setup.py", "--quiet", *args, env=env)


def forward(path: Path) -> str:
    return str(path).replace("\\", "/")


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def append(path: Path, text: str) -> None:
    with path.open("a", encoding="utf-8", newline="\n") as file:
        file.write(text + "\n")


def stamps(box: Sandbox, skill: str) -> list[str]:
    """Each different stamp in a generated skill's commands."""
    text = read(box.generated / "skills" / skill / "SKILL.md")
    return sorted(set(re.findall(rf"--skill {skill} --stamp ([0-9a-f]+)", text)))


def test_first_run_exits_0_and_says_it_uses_the_test_profile(first: First) -> None:
    assert first.run.code == 0, str(first.run)
    assert first.run.has_line(r"^TEST\s"), str(first.run)


def test_fills_in_every_placeholder(box: Sandbox) -> None:
    left = [
        str(path)
        for path in box.generated.rglob("*")
        if path.is_file() and re.search(r"\{\{[A-Z_]+\}\}", path.read_text(errors="replace"))
    ]
    assert (box.generated / "skills" / "handoff" / "SKILL.md").is_file()
    assert left == []


def test_writes_this_copys_paths_into_the_commands_and_pre_approvals(box: Sandbox) -> None:
    tools = forward(box.tools)
    skill = read(box.generated / "skills" / "handoff" / "SKILL.md")
    assert f"Bash({tools}/internal/.python/python.exe -I {tools}/sync.py)" in skill
    assert f"{tools}/internal/.generated/skills/handoff/template.md" in skill
    scripts = box.generated / "shared-skill-scripts"
    assert (scripts / "facts.py").is_file() and (scripts / "prepare.py").is_file()
    prepare = re.escape(
        f"Bash({tools}/internal/.python/python.exe -I {tools}/internal/.generated/"
        "shared-skill-scripts/prepare.py --skill handoff --stamp "
    )
    assert re.search(
        prepare + r"[0-9a-f]{12} --fetch auto handoff environment newer-commits\)", skill
    )


def test_no_skill_starts_powershell(box: Sandbox) -> None:
    # Nothing needs it, and Claude Code's PowerShell tool asks before running any command that
    # starts another PowerShell, even a pre-approved one.
    starts = [
        str(path)
        for path in (box.generated / "skills").rglob("*")
        if path.is_file() and re.search(r"\bpwsh\b|powershell\.exe", read(path), re.IGNORECASE)
    ]
    assert starts == []


def test_links_internal_python_to_the_python_it_finds(box: Sandbox) -> None:
    assert link_target(box.tools / "internal" / ".python") == box.python_bin


def test_adds_nothing_to_the_root(first: First) -> None:
    # The root holds what must be there (AGENTS.md says what). local-settings.json, setup's one
    # file there, was already written for the test profile.
    added = {entry.name for entry in first.box.tools.iterdir()} - first.root_before
    assert added == set()


def test_stamps_each_skills_commands_with_one_stamp_of_its_own(box: Sandbox) -> None:
    handoff, knowledge = stamps(box, "handoff"), stamps(box, "knowledge")
    assert len(handoff) == 1 and len(knowledge) == 1, (handoff, knowledge)
    assert re.fullmatch(r"[0-9a-f]{12}", handoff[0])
    assert handoff != knowledge


def test_notes_each_skills_template_right_after_its_frontmatter(box: Sandbox) -> None:
    tools, content = forward(box.tools), forward(box.content)
    files = sorted((box.generated / "skills").glob("*/SKILL.md"))
    unnoted = []
    for file in files:
        name = file.parent.name
        text = read(file)
        close = text.find("\n---\n", 3)
        after = text[close + 5 :] if close > 0 else ""
        if not (
            text.startswith(f"---\nname: {name}\n")
            and after.startswith(f"{MARKER}{tools}/templates/skills/{name}/. Do not edit this copy")
            and f"skills of your own go in {content}/skills/. -->" in text
        ):
            unnoted.append(str(file))
    assert len(files) >= 2
    assert unnoted == []


def test_notes_the_operating_rules_template_at_the_top(box: Sandbox) -> None:
    tools, content = forward(box.tools), forward(box.content)
    rules = read(box.generated / "operating-rules" / "operating-rules.md")
    source = f"{MARKER}{tools}/templates/operating-rules/operating-rules.md. Do not edit this copy"
    assert rules.startswith(source)
    assert f"Put rules of your own in {content}/global-rules/global-rules.md;" in rules
    assert "\n\n# Private repo: dev-home (rules loaded)" in rules


def test_notes_no_other_generated_file(box: Sandbox) -> None:
    # Such as the handoff template, which is copied into every new handoff.
    noted = {*(box.generated / "skills").glob("*/SKILL.md")}
    noted.add(box.generated / "operating-rules" / "operating-rules.md")
    extra = [
        str(path)
        for path in box.generated.rglob("*")
        if path.is_file() and path not in noted and MARKER in path.read_text(errors="replace")
    ]
    assert extra == []


@pytest.mark.parametrize("folder", [".claude/skills", ".agents/skills"])
def test_links_each_skill(box: Sandbox, folder: str) -> None:
    skills = box.profile / folder
    assert link_target(skills / "handoff") == box.generated / "skills" / "handoff"
    assert link_target(skills / "knowledge") == box.generated / "skills" / "knowledge"
    assert link_target(skills / "mine") == box.content / "skills" / "mine"


def test_links_the_rules_for_claude_code(box: Sandbox) -> None:
    rules = box.profile / ".claude" / "rules"
    assert link_target(rules / "dev-home-operating-rules") == box.generated / "operating-rules"
    assert link_target(rules / "dev-home-global-rules") == box.content / "global-rules"


def test_writes_codexs_rules_with_one_note_then_the_operating_then_the_global(box: Sandbox) -> None:
    tools, content = forward(box.tools), forward(box.content)
    codex = read(box.profile / ".codex" / "AGENTS.md")
    source = (
        f"{MARKER}{tools}/templates/operating-rules/operating-rules.md and "
        f"{content}/global-rules/global-rules.md. "
    )
    operating = codex.find("# Private repo: dev-home (rules loaded)")
    assert codex.startswith(source), codex
    assert "Put rules of your own in the second file;" in codex
    assert codex.count(MARKER) == 1
    assert 0 < operating < codex.find("- Personal rule one.")


def test_a_second_run_changes_nothing_and_prints_nothing_else(box: Sandbox) -> None:
    result = setup(box)
    assert result.code == 0, str(result)
    assert [line for line in result.lines if not line.startswith("TEST")] == [], str(result)


def test_a_skills_stamp_follows_its_skill_file_only(box: Sandbox) -> None:
    folder = box.tools / "templates" / "skills" / "handoff"
    skill, template = folder / "SKILL.md", folder / "template.md"
    skill_bytes, template_bytes = skill.read_bytes(), template.read_bytes()
    stamp = stamps(box, "handoff")
    try:
        append(template, "- A line added to the template.")
        setup(box)
        after_template = stamps(box, "handoff")
        append(skill, "A line added to the skill.")
        setup(box)
        after_skill = stamps(box, "handoff")
    finally:
        skill.write_bytes(skill_bytes)
        template.write_bytes(template_bytes)
    result = setup(box)
    assert after_template == stamp
    assert len(after_skill) == 1 and after_skill != stamp
    assert result.code == 0 and stamps(box, "handoff") == stamp, (
        "the stamp comes back with the text"
    )


def test_the_python_link(box: Sandbox) -> None:
    link = box.tools / "internal" / ".python"
    # Re-pointed once its python.exe is gone.
    no_python = box.root / "no-python"
    no_python.mkdir()
    remove_link(link)
    make_junction(link, no_python)
    result = setup(box)
    assert result.code == 0 and result.has_line(r"^LINKED\s+Python for the skills"), str(result)
    assert link_target(link) == box.python_bin
    # Reported when no Python 3.12 or later is found.
    remove_link(box.python_bin)
    try:
        result = setup(box)
    finally:
        make_junction(box.python_bin, Path(sys.base_prefix))
    pattern = r"^PROBLEM\s+Python for the skills: no Python 3\.12 or later"
    assert result.code == 1 and result.has_line(pattern), str(result)
    # Left alone when it isn't a link.
    remove_link(link)
    link.mkdir()
    try:
        result = setup(box)
        assert result.code == 1 and result.has_line("is not a link"), str(result)
        assert link.is_dir() and link_target(link) is None
    finally:
        link.rmdir()
    setup(box)
    assert link_target(link) == box.python_bin, "linked again once the folder is gone"


def test_the_generated_folder(box: Sandbox) -> None:
    # Python's bytecode cache stays beside the scripts, a link that isn't setup's stays and
    # nothing behind it changes, and a folder whose templates are gone goes, cache and all.
    cache = box.generated / "shared-skill-scripts" / "__pycache__" / "facts.cpython-399.pyc"
    write_text(cache, "cache")
    outside = box.root / "outside"
    write_text(outside / "keep.txt", "keep\n")
    top_link = box.generated / "someone-elses-link"
    inner_link = box.generated / "skills" / "handoff" / "someone-elses-link"
    make_junction(top_link, outside)
    make_junction(inner_link, outside)
    old_scripts = box.generated / "old-scripts"
    write_text(old_scripts / "old.py", "pass\n")
    write_text(old_scripts / "__pycache__" / "old.cpython-399.pyc", "cache")
    try:
        result = setup(box)
        assert result.code == 0 and cache.is_file(), str(result)
        assert (outside / "keep.txt").exists()
        assert link_target(top_link) is not None and link_target(inner_link) is not None
        assert not old_scripts.exists()
    finally:
        remove_link(top_link)
        remove_link(inner_link)
    # A generated folder that is a link is reported, and nothing is written through it.
    scripts = box.generated / "shared-skill-scripts"
    shutil.rmtree(scripts)
    make_junction(scripts, outside)
    try:
        result = setup(box)
        assert result.code == 1 and result.has_line("is a link, so setup left it alone"), str(
            result
        )
        assert [p.name for p in outside.iterdir()] == ["keep.txt"]
    finally:
        remove_link(scripts)
    result = setup(box)
    assert result.code == 0 and (scripts / "facts.py").is_file(), str(result)


def test_rewrites_and_removes_read_only_generated_files(box: Sandbox) -> None:
    # Setup's own files, so a read-only mark doesn't stop it.
    skill = box.generated / "skills" / "handoff"
    stale = skill / "stale.md"
    write_text(stale, "a file whose template is gone\n")
    template = skill / "template.md"
    generated_bytes = template.read_bytes()
    write_text(template, "an edit setup puts right\n")
    for path in (stale, template):
        path.chmod(stat.S_IREAD)
    try:
        result = setup(box)
    finally:
        for path in (stale, template):
            if path.exists():
                path.chmod(stat.S_IREAD | stat.S_IWRITE)
    assert result.code == 0, str(result)
    assert not stale.exists()
    assert template.read_bytes() == generated_bytes


def test_never_writes_through_a_link_to_a_generated_file(box: Sandbox) -> None:
    generated_rules = box.generated / "operating-rules" / "operating-rules.md"
    someone_elses = box.root / "someone-elses-file.md"
    write_text(someone_elses, "keep\n")
    before = generated_rules.read_bytes()
    generated_rules.unlink()
    try:
        try:
            generated_rules.symlink_to(someone_elses)
        except OSError:
            pytest.skip("Creating a file symlink needs admin rights or Developer Mode on this PC.")
        result = setup(box)
        kept = read(someone_elses)
    finally:
        if generated_rules.is_symlink():
            generated_rules.unlink()
        generated_rules.write_bytes(before)
    assert result.code == 1 and result.has_line("is a link, so setup left it alone"), str(result)
    assert kept == "keep\n"


def test_reports_missing_settings_without_changing_them(box: Sandbox) -> None:
    claude = box.profile / ".claude" / "settings.json"
    codex = box.profile / ".codex" / "config.toml"
    claude_bytes, codex_bytes = claude.read_bytes(), codex.read_bytes()
    write_text(claude, "{}\n")
    write_text(codex, "")
    try:
        result = setup(box)
        unchanged = read(claude) == "{}\n" and read(codex) == ""
    finally:
        claude.write_bytes(claude_bytes)
        codex.write_bytes(codex_bytes)
    assert result.code == 1, str(result)
    assert result.has_line("additionalDirectories") and result.has_line("writable_roots"), str(
        result
    )
    assert unchanged


def test_reads_a_settings_file_with_comments_that_has_the_folders(box: Sandbox) -> None:
    # Setup won't edit a file with comments, but can still see the folders in it.
    claude = box.profile / ".claude" / "settings.json"
    before = claude.read_bytes()
    folders = json.dumps([str(box.content), str(box.tools)])
    write_text(
        claude, f'{{\n  // mine\n  "permissions": {{"additionalDirectories": {folders}}}\n}}\n'
    )
    try:
        result = setup(box)
    finally:
        claude.write_bytes(before)
    assert result.code == 0, str(result)


def test_a_settings_file_it_cant_read_is_reported_and_setup_goes_on(box: Sandbox) -> None:
    claude = box.profile / ".claude" / "settings.json"
    before = claude.read_bytes()
    claude.unlink()
    claude.mkdir()
    try:
        result = setup(box)
    finally:
        claude.rmdir()
        claude.write_bytes(before)
    assert result.code == 1, str(result)
    assert result.has_line(r"^PROBLEM\s+.*settings\.json could not be read"), str(result)
    assert not result.has_line("setup.py stopped"), str(result)


def remove_claude_folder(folder: Path) -> None:
    """A Claude folder setup linked into: each link first, then the folder."""
    for links in (folder / "skills", folder / "rules"):
        for link in links.iterdir() if links.is_dir() else []:
            remove_link(link)
    shutil.rmtree(folder)


def test_the_claude_folder_in_claude_config_dir(box: Sandbox) -> None:
    # A test profile takes it only from inside itself. One with no answer is set up anyway, so
    # the session's account keeps working, with advice that works from a terminal, where that
    # variable usually isn't set.
    session = box.profile / ".claude-second"
    other = box.profile / "claude-alt"
    outside = box.root / "outside-claude"
    for folder in (session, other, outside):
        write_text(folder / "settings.json", "{}\n")
    settings_path = box.tools / "local-settings.json"
    settings_text = read(settings_path)
    unasked = (
        r"^PROBLEM\s+Setup hasn't asked yet whether to set up the Claude Code folder "
        r".*\.claude-second\. Run "
    )
    try:
        result = setup(box, env={"CLAUDE_CONFIG_DIR": str(outside)})
        assert not (outside / "skills").exists(), str(result)
        # Every quiet run names a ~/.claude-* folder nobody has answered for.
        assert result.code == 1 and result.has_line(unasked), str(result)
        result = setup(box, env={"CLAUDE_CONFIG_DIR": str(session)})
        assert link_target(session / "skills" / "handoff") == box.generated / "skills" / "handoff"
        pattern = (
            r"^PROBLEM\s+Claude Code settings in \.claude-second: .* setup hasn't asked yet "
            r"whether to set it up\. Run setup\.py without --quiet: it asks about the folder"
        )
        assert result.code == 1 and result.has_line(pattern), str(result)
        assert not result.has_line("claudeConfigDirs"), str(result)
        # A folder setup doesn't offer is added to the list by hand.
        result = setup(box, env={"CLAUDE_CONFIG_DIR": str(other)})
        pattern = (
            r'^PROBLEM\s+Claude Code settings in claude-alt: .* Add "~/claude-alt" to '
            r"claudeConfigDirs in .*local-settings\.json, then run setup\.py without --quiet, "
            "and it offers"
        )
        assert result.code == 1 and result.has_line(pattern), str(result)
        listed = json.loads(settings_text)
        listed["claudeConfigDirs"] = ["~/.claude-second"]
        write_text(settings_path, json.dumps(listed, indent=2) + "\n")
        result = setup(box, env={"CLAUDE_CONFIG_DIR": str(session)})
        pattern = (
            r"^PROBLEM\s+Claude Code settings in \.claude-second: .* Run setup\.py without "
            "--quiet, and it offers"
        )
        assert result.code == 1 and result.has_line(pattern), str(result)
        assert not result.has_line("claudeConfigDirs"), str(result)
        assert not result.has_line("hasn't asked"), str(result)
    finally:
        write_text(settings_path, settings_text)
        for folder in (session, other):
            remove_claude_folder(folder)
        shutil.rmtree(outside)


def test_a_claude_folder_with_a_no_is_left_alone_even_from_a_session_there(box: Sandbox) -> None:
    session = box.profile / ".claude-declined"
    write_text(session / "settings.json", "{}\n")
    settings_path = box.tools / "local-settings.json"
    settings_text = read(settings_path)
    declined = json.loads(settings_text)
    declined["declinedClaudeConfigDirs"] = ["~/.claude-declined"]
    write_text(settings_path, json.dumps(declined, indent=2) + "\n")
    try:
        result = setup(box, env={"CLAUDE_CONFIG_DIR": str(session)})
    finally:
        write_text(settings_path, settings_text)
        remove_claude_folder(session)
    assert result.code == 0, str(result)
    assert not result.has_line("claude-declined"), str(result)


def test_a_changed_template_reaches_the_generated_copy_and_codexs_rules(box: Sandbox) -> None:
    template = box.tools / "templates" / "operating-rules" / "operating-rules.md"
    before = template.read_bytes()
    append(template, "- A line added to the operating rules.")
    try:
        result = setup(box)
        codex = read(box.profile / ".codex" / "AGENTS.md")
        generated = read(box.generated / "operating-rules" / "operating-rules.md")
    finally:
        template.write_bytes(before)
        setup(box)
    assert "A line added to the operating rules." in codex, str(result)
    assert "A line added to the operating rules." in generated


def test_frontmatter_that_ends_in_an_unusual_way(box: Sandbox) -> None:
    # One closing line with trailing spaces, and one with no closing line at all.
    spaced = box.tools / "templates" / "skills" / "spaced"
    unclosed = box.tools / "templates" / "skills" / "unclosed"
    write_text(
        spaced / "SKILL.md",
        "---\nname: spaced\ndescription: Trailing spaces.\n---  \n\n# Spaced\n",
    )
    write_text(unclosed / "SKILL.md", "---\nname: unclosed\ndescription: Never ends.\n")
    try:
        result = setup(box)
        spaced_text = read(box.generated / "skills" / "spaced" / "SKILL.md")
        unclosed_text = read(box.generated / "skills" / "unclosed" / "SKILL.md")
    finally:
        shutil.rmtree(spaced)
        shutil.rmtree(unclosed)
    assert f"\n---  \n{MARKER}" in spaced_text
    assert result.code == 1 and result.has_line(r"^PROBLEM\s.*unclosed.*no closing"), str(result)
    assert unclosed_text.startswith("---\nname: unclosed\n") and MARKER not in unclosed_text
    result = setup(box)
    assert result.code == 0, str(result)
    assert not (box.generated / "skills" / "unclosed").exists(), "removes those two again"


def test_removes_a_generated_folder_with_no_templates_and_moves_a_link_off_it(
    box: Sandbox,
) -> None:
    # The generated folder from an older layout, with the operating rules link still in it.
    old_rules = box.generated / "rules"
    write_text(old_rules / "core.md", "old core rules\n")
    link = box.profile / ".claude" / "rules" / "dev-home-operating-rules"
    remove_link(link)
    make_junction(link, old_rules)
    result = setup(box)
    assert result.code == 0 and not old_rules.exists(), str(result)
    assert link_target(link) == box.generated / "operating-rules"


def test_a_template_file_becomes_a_folder_and_back(box: Sandbox) -> None:
    folder = box.tools / "templates" / "skills" / "handoff"
    to_folder, to_file = folder / "to-folder", folder / "to-file"
    write_text(to_folder, "a file\n")
    write_text(to_file / "inner.md", "a folder\n")
    try:
        setup(box)
        to_folder.unlink()
        write_text(to_folder / "inner.md", "now a folder\n")
        result = setup(box)
        assert result.code == 0, str(result)
        assert (box.generated / "skills" / "handoff" / "to-folder" / "inner.md").is_file()
        shutil.rmtree(to_file)
        write_text(to_file, "now a file\n")
        result = setup(box)
        assert result.code == 0 and (box.generated / "skills" / "handoff" / "to-file").is_file()
    finally:
        if to_file.is_file():
            to_file.unlink()
        shutil.rmtree(to_folder, ignore_errors=True)
        setup(box)


def test_a_removed_skill_loses_its_generated_copy_and_its_links(box: Sandbox) -> None:
    knowledge = box.tools / "templates" / "skills" / "knowledge"
    kept = box.root / "knowledge-template"
    shutil.move(knowledge, kept)
    try:
        result = setup(box)
        assert not (box.generated / "skills" / "knowledge").exists(), str(result)
        assert link_target(box.profile / ".claude" / "skills" / "knowledge") is None
        assert link_target(box.profile / ".agents" / "skills" / "knowledge") is None
    finally:
        shutil.move(kept, knowledge)
        setup(box)


def test_replaces_a_link_whose_target_is_gone(box: Sandbox) -> None:
    link = box.profile / ".claude" / "skills" / "handoff"
    gone = box.root / "gone"
    gone.mkdir()
    remove_link(link)
    make_junction(link, gone)
    gone.rmdir()
    setup(box)
    assert link_target(link) == box.generated / "skills" / "handoff"


def test_leaves_alone_a_codex_rules_file_it_did_not_write(box: Sandbox) -> None:
    rules = box.profile / ".codex" / "AGENTS.md"
    before = rules.read_bytes()
    write_text(rules, "my own codex rules\n")
    try:
        result = setup(box)
        kept = read(rules) == "my own codex rules\n"
    finally:
        rules.write_bytes(before)
    assert result.code == 1 and result.has_line("setup did not write it"), str(result)
    assert kept


def test_leaves_alone_a_codex_rules_link_whose_target_exists(box: Sandbox) -> None:
    rules = box.profile / ".codex" / "AGENTS.md"
    before = rules.read_bytes()
    rules.unlink()
    try:
        try:
            rules.symlink_to(box.content / "global-rules" / "global-rules.md")
        except OSError:
            pytest.skip("Creating a file symlink needs admin rights or Developer Mode on this PC.")
        result = setup(box)
        assert result.code == 1 and result.has_line("Left alone"), str(result)
        assert link_target(rules) is not None
    finally:
        if rules.is_symlink():
            rules.unlink()
        rules.write_bytes(before)


def test_reports_a_placeholder_it_does_not_know(box: Sandbox) -> None:
    template = box.tools / "templates" / "skills" / "handoff" / "template.md"
    before = template.read_bytes()
    append(template, "{{NOT_A_PLACEHOLDER}}")
    try:
        result = setup(box)
    finally:
        template.write_bytes(before)
        setup(box)
    assert result.code == 1 and result.has_line("NOT_A_PLACEHOLDER"), str(result)


def test_a_personal_skill_with_a_tooling_skills_name(box: Sandbox) -> None:
    clash = box.content / "skills" / "handoff"
    write_text(clash / "SKILL.md", "---\nname: handoff\ndescription: A clash.\n---\n")
    try:
        result = setup(box)
    finally:
        shutil.rmtree(clash)
    assert result.code == 1 and result.has_line("same name"), str(result)
    assert ".generated" in str(link_target(box.profile / ".claude" / "skills" / "handoff"))


def test_refuses_a_dev_home_path_with_a_space_and_keeps_the_settings(box: Sandbox) -> None:
    settings = box.tools / "local-settings.json"
    before = read(settings)
    result = setup(box, "--content-dir", str(box.root / "has space"))
    assert result.code == 1 and result.has_line("space"), str(result)
    assert read(settings) == before


def test_a_new_dev_home_folder_is_saved_with_test_home_dir_kept(box: Sandbox) -> None:
    settings = box.tools / "local-settings.json"
    before = read(settings)
    try:
        result = setup(box, "--content-dir", str(box.root / "another-dev-home"))
        saved = json.loads(read(settings))
    finally:
        write_text(settings, before)
    assert saved["contentDir"].endswith("another-dev-home")
    assert saved["testHomeDir"] == forward(box.profile)
    # With --quiet, a missing dev-home is reported instead of asked about.
    assert result.code == 1 and result.has_line("There is no dev-home"), str(result)


def write_starter_files(folder: Path) -> None:
    """The files every dev-home starts with, which setup checks for."""
    write_text(folder / "global-rules" / "global-rules.md", "# My rules\n")
    write_text(folder / "knowledge" / "README.md", "# Knowledge base\n")


def test_stops_at_a_folder_that_doesnt_look_like_a_dev_home(box: Sandbox) -> None:
    # Such as a project's repo, named by mistake: setup must not turn its signing off.
    project = box.root / "a-project"
    git("init", "--quiet", "-b", "main", str(project))
    write_text(project / "README.md", "# a project\n")
    git("-C", str(project), "add", "--all")
    git("-C", str(project), "commit", "--quiet", "-m", "test: project")
    settings = box.tools / "local-settings.json"
    before = read(settings)
    try:
        result = setup(box, "--content-dir", str(project))
    finally:
        write_text(settings, before)
    pattern = (
        r"^PROBLEM\s+.*a-project doesn't look like a dev-home: it has no "
        r"global-rules/global-rules\.md or knowledge/README\.md, which every dev-home starts with"
    )
    assert result.code == 1 and result.has_line(pattern), str(result)
    assert read(settings) == before
    assert "gpgsign" not in read(project / ".git" / "config")


def test_keeps_settings_it_doesnt_know_and_leaves_auto_update_out_until_answered(
    box: Sandbox,
) -> None:
    # A quiet run asks nothing, so a save must not look like an answer.
    settings = box.tools / "local-settings.json"
    before = read(settings)
    edited = json.loads(before)
    del edited["autoUpdate"]
    edited["somethingNewer"] = {"kept": True}
    write_text(settings, json.dumps(edited, indent=2) + "\n")
    try:
        setup(box, "--content-dir", str(box.root / "yet-another-dev-home"))
        saved = json.loads(read(settings))
    finally:
        write_text(settings, before)
    assert saved["contentDir"].endswith("yet-another-dev-home")
    assert saved["somethingNewer"] == {"kept": True}
    assert "autoUpdate" not in saved
    assert "declinedClaudeConfigDirs" not in saved


def test_reports_a_check_interval_that_isnt_whole_hours(box: Sandbox) -> None:
    settings = box.tools / "local-settings.json"
    before = read(settings)
    edited = json.loads(before)
    edited.update({"updateCheckHours": "6", "contentCheckHours": -1})
    write_text(settings, json.dumps(edited, indent=2) + "\n")
    try:
        result = setup(box)
    finally:
        write_text(settings, before)
    assert result.code == 1, str(result)
    for key, value, default in (("updateCheckHours", '"6"', 24), ("contentCheckHours", "-1", 12)):
        pattern = (
            rf"^PROBLEM\s+{key} in .* is {value}, which isn't a whole number of hours, 0 or "
            rf"more, so it counts as {default}\."
        )
        assert result.has_line(pattern), str(result)


@pytest.mark.parametrize(
    ("value", "hours", "usable"),
    [(None, 12, True), (0, 0, True), (6, 6, True), (True, 12, False), (1.5, 12, False)],
)
def test_reads_a_check_interval(box: Sandbox, value: object, hours: int, usable: bool) -> None:
    data = {} if value is None else {"contentCheckHours": value}
    found = shared_module(box, "settings").hours_setting(data, "contentCheckHours")
    assert found == (hours, usable)


def test_stops_at_a_settings_file_that_isnt_an_object(box: Sandbox) -> None:
    settings = box.tools / "local-settings.json"
    before = read(settings)
    write_text(settings, "[]\n")
    try:
        result = setup(box)
        kept = read(settings)
    finally:
        write_text(settings, before)
    assert result.code == 1, str(result)
    assert result.has_line(r"^PROBLEM\s+.* could not be read as a JSON object of settings"), str(
        result
    )
    assert kept == "[]\n"


def test_says_so_when_it_cant_save_its_settings(box: Sandbox) -> None:
    settings = box.tools / "local-settings.json"
    before = read(settings)
    settings.chmod(stat.S_IREAD)
    try:
        result = setup(box, "--content-dir", str(box.root / "unsaved-dev-home"))
    finally:
        settings.chmod(stat.S_IREAD | stat.S_IWRITE)
        write_text(settings, before)
    assert result.has_line(r"^PROBLEM\s+Could not save this PC's settings in "), str(result)
    # The rest of the run still goes on.
    assert result.has_line("There is no dev-home"), str(result)


@pytest.mark.parametrize(
    ("text", "says"),
    [
        (None, r"dev-home has no answer yet to whether it's in active use anywhere besides this "),
        ('{"other": 1}\n', r"dev-home has no answer yet"),
        ("[true]\n", r"dev-home\.json could not be read as a JSON object of settings, so setup "),
    ],
    ids=["no file", "no answer", "not an object"],
)
def test_a_quiet_run_reports_dev_home_json_with_no_answer_and_changes_nothing(
    box: Sandbox, text: str | None, says: str
) -> None:
    path = box.content / "dev-home.json"
    before = path.read_bytes()
    if text is None:
        path.unlink()
    else:
        write_text(path, text)
    try:
        result = setup(box)
        after = path.read_text(encoding="utf-8") if path.exists() else None
    finally:
        path.write_bytes(before)
    assert result.code == 1 and result.has_line(rf"^PROBLEM\s+.*{says}"), str(result)
    assert after == text


# --configure without a console, as an agent runs it.


@pytest.fixture
def settings_kept(box: Sandbox) -> Iterator[Path]:
    """local-settings.json, put back as it was, and its backups removed, after the test."""
    path = box.tools / "local-settings.json"
    before = path.read_bytes()
    yield path
    path.write_bytes(before)
    for backup in path.parent.glob("local-settings.json.bak-*"):
        backup.unlink()


def test_configure_alone_shows_the_settings_and_how_to_change_them(
    box: Sandbox, settings_kept: Path
) -> None:
    before = read(settings_kept)
    result = run_python(box, "setup.py", "--configure")
    assert result.code == 0, str(result)
    assert result.has_line(r"^dev-home-tools settings$"), str(result)
    assert result.has_line(r"^\s+2\s+Install dev-home-tools updates automatically\s+no$"), str(
        result
    )
    assert result.has_line(r"^\s+6\s+Copies of dev-home in active use\s+several$"), str(result)
    assert result.has_line(r"^\s+multiMachine=true\|false\s"), str(result)
    assert not result.has_line("All checks passed"), str(result)
    assert read(settings_kept) == before


def test_configure_changes_one_setting_with_a_backup(box: Sandbox, settings_kept: Path) -> None:
    before = read(settings_kept)
    result = setup_configure(box, "autoUpdate=true")
    assert result.code == 0, str(result)
    assert result.has_line(r"^CHANGE\s+This PC's settings: "), str(result)
    assert result.has_line(r'^\s+\+\s+"autoUpdate": true,$'), str(result)
    assert result.has_line(r"^SET\s+This PC's settings: .* Backup of the old file: "), str(result)
    assert json.loads(read(settings_kept))["autoUpdate"] is True
    backups = list(settings_kept.parent.glob("local-settings.json.bak-*"))
    assert len(backups) == 1 and read(backups[0]) == before
    # A second run finds it already set.
    again = setup_configure(box, "autoUpdate=true")
    assert again.code == 0 and again.has_line(r"^OK\s+autoUpdate is already set that way"), str(
        again
    )


def test_git_ignores_this_pcs_settings_and_what_saving_them_leaves_beside_them(
    box: Sandbox,
) -> None:
    # They hold this PC's paths, and the repo is public.
    repo = box.root / "ignore-check"
    git("init", "--quiet", str(repo))
    shutil.copyfile(box.tools / ".gitignore", repo / ".gitignore")
    names = [
        "local-settings.json",
        "local-settings.json.bak-20261008-143000",
        "local-settings.json.dev-home-new",
    ]
    assert git("-C", str(repo), "check-ignore", "--no-index", *names) == names


def setup_configure(box: Sandbox, *args: str) -> Run:
    return run_python(box, "setup.py", "--configure", *args)


def test_configure_what_if_shows_the_change_and_makes_none(
    box: Sandbox, settings_kept: Path
) -> None:
    before = read(settings_kept)
    result = setup_configure(box, "contentCheckHours=6", "--what-if")
    assert result.code == 0, str(result)
    assert result.has_line(r'^\s+\+\s+"contentCheckHours": 6$'), str(result)
    assert result.has_line(r"^What if: Save this PC's settings"), str(result)
    assert read(settings_kept) == before


def test_the_dev_home_skills_configure_commands_work_as_written(
    box: Sandbox, settings_kept: Path
) -> None:
    # Taken word for word from the generated skill: show, preview, then change. A shell drops the
    # single quotes, so the setting reaches setup as one word.
    text = read(box.generated / "skills" / "dev-home" / "SKILL.md")
    configure = f"{box.python.as_posix()} -I {forward(box.tools)}/setup.py --configure"
    commands = re.findall(rf"`({re.escape(configure)}[^`]*)`", text)
    assert len(commands) == 3, commands
    show, preview, change = (c.replace("'<name>=<value>'", "contentCheckHours=6") for c in commands)
    before = read(settings_kept)
    shown = run_command(box, show, cwd=box.root)
    assert shown.code == 0 and shown.has_line(r"^dev-home-tools settings$"), str(shown)
    previewed = run_command(box, preview, cwd=box.root)
    assert previewed.has_line(r'^\s+\+\s+"contentCheckHours": 6$'), str(previewed)
    assert read(settings_kept) == before
    changed = run_command(box, change, cwd=box.root)
    assert changed.code == 0, str(changed)
    assert json.loads(read(settings_kept))["contentCheckHours"] == 6


@pytest.mark.parametrize(
    ("setting", "says"),
    [
        ("colour=red", r"There is no setting named colour\."),
        ("autoUpdate=maybe", r"autoUpdate is true or false, not maybe\."),
        ("updateCheckHours=-1", r"updateCheckHours is a whole number of hours, 0 or more"),
        ("claudeConfigDirs=~/.claude-x", r"claudeConfigDirs changes one folder at a time"),
        ("autoUpdate+=true", r"autoUpdate is set with =, as in autoUpdate=<value>\."),
        ("claudeConfigDirs+=~/.claude-missing", r"There is no Claude Code folder at "),
        ("nothing", r"--configure takes one setting as <name>=<value>, not nothing\."),
    ],
)
def test_configure_refuses_a_setting_it_cant_make(
    box: Sandbox, settings_kept: Path, setting: str, says: str
) -> None:
    before = read(settings_kept)
    result = setup_configure(box, setting)
    assert result.code == 1, str(result)
    assert result.has_line(rf"^PROBLEM\s+{says}.* Nothing was changed\.$"), str(result)
    assert result.has_line(r"^\s+contentDir=<folder>\s"), str(result)
    assert read(settings_kept) == before


def test_configure_sets_content_dir_only_to_a_dev_home(box: Sandbox, settings_kept: Path) -> None:
    other = box.root / "configured-dev-home"
    write_starter_files(other)
    git("init", "--quiet", "-b", "main", str(other))
    plain = box.root / "configured-plain-folder"
    write_text(plain / "notes.md", "not a dev-home\n")
    refused = setup_configure(box, f"contentDir={plain}")
    accepted = setup_configure(box, f"contentDir={other}", "--what-if")
    assert refused.code == 1 and refused.has_line(r"configured-plain-folder isn't a dev-home"), str(
        refused
    )
    assert accepted.has_line(r'^\s+\+\s+"contentDir": ".*configured-dev-home",$'), str(accepted)


def test_configure_adds_and_removes_a_claude_folder(box: Sandbox, settings_kept: Path) -> None:
    added = box.profile / ".claude-configured"
    write_text(added / "settings.json", "{}\n")
    try:
        result = setup_configure(box, "claudeConfigDirs+=~/.claude-configured")
        linked = link_target(added / "skills" / "handoff")
        listed = json.loads(read(settings_kept))["claudeConfigDirs"]
        removed = setup_configure(box, "claudeConfigDirs-=~/.claude-configured")
        saved = json.loads(read(settings_kept))
    finally:
        remove_claude_folder(added)
    assert result.has_line(r"^SET\s+This PC's settings"), str(result)
    assert listed == ["~/.claude-configured"]
    assert linked == box.generated / "skills" / "handoff"
    assert removed.code == 0, str(removed)
    assert saved["claudeConfigDirs"] == []
    assert saved["declinedClaudeConfigDirs"] == ["~/.claude-configured"]


def test_configure_switches_copies_then_commits_and_pushes_it(box: Sandbox) -> None:
    # An agent's change was approved in chat, so nothing is asked.
    result = setup_configure(box, "multiMachine=false")
    back = setup_configure(box, "multiMachine=true")
    subjects = git("-C", str(box.remote), "log", "-2", "--format=%s", "main")
    assert result.code == 0, str(result)
    assert result.has_line(r"^CHANGE\s+dev-home's copies: "), str(result)
    assert result.has_line(r'^\s+\+\s+"multiMachine": false$'), str(result)
    assert result.has_line(r'^COMMITTED\s+"dev-home: one active copy"'), str(result)
    assert result.has_line(r"^PUSHED\s+1 commit to GitHub\."), str(result)
    assert back.code == 0, str(back)
    assert subjects == ["dev-home: several active copies", "dev-home: one active copy"]


def test_configure_doesnt_go_with_quiet(box: Sandbox) -> None:
    result = setup(box, "--configure", "autoUpdate=true")
    assert result.code == 1, str(result)
    assert result.has_line(r"^PROBLEM\s+--configure doesn't go with --quiet"), str(result)


def test_reports_a_dev_home_repo_with_no_commits(box: Sandbox) -> None:
    # What a first run leaves when git init worked but the commit didn't: the starter's files,
    # with no commit.
    unfinished = box.root / "unfinished-dev-home"
    git("init", "--quiet", "-b", "main", str(unfinished))
    write_starter_files(unfinished)
    settings = box.tools / "local-settings.json"
    before = read(settings)
    try:
        result = setup(box, "--content-dir", str(unfinished))
    finally:
        write_text(settings, before)
    assert result.code == 1 and result.has_line("no commits"), str(result)


def test_reports_a_dev_home_git_cant_read_without_advice_to_delete_it(box: Sandbox) -> None:
    # A repo git refuses to read says nothing about what's in it.
    unreadable = box.root / "unreadable-dev-home"
    git("init", "--quiet", "-b", "main", str(unreadable))
    write_starter_files(unreadable)
    git("-C", str(unreadable), "add", "--all")
    git("-C", str(unreadable), "commit", "--quiet", "-m", "test: content")
    append(unreadable / ".git" / "config", "[broken")
    settings = box.tools / "local-settings.json"
    before = read(settings)
    try:
        result = setup(box, "--content-dir", str(unreadable))
    finally:
        write_text(settings, before)
    assert result.code == 1 and result.has_line("could not read"), str(result)
    assert not result.has_line("delete"), str(result)


@pytest.mark.parametrize("form", ["root", "dot-dot"])
def test_refuses_a_dev_home_at_the_root_of_a_drive(box: Sandbox, form: str) -> None:
    # Hand-edited, because setup itself never saves a path that fails its checks. A path that
    # leads to the root counts as the root.
    settings = box.tools / "local-settings.json"
    before = read(settings)
    edited = json.loads(before)
    root = Path(box.root.anchor).as_posix()
    edited["contentDir"] = root if form == "root" else f"{root}dev-home/.."
    write_text(settings, json.dumps(edited, indent=2) + "\n")
    try:
        result = setup(box)
    finally:
        write_text(settings, before)
    assert result.code == 1 and result.has_line("root of a drive"), str(result)


def test_refuses_a_dev_home_inside_dev_home_tools(box: Sandbox) -> None:
    settings = box.tools / "local-settings.json"
    before = read(settings)
    result = setup(box, "--content-dir", str(box.tools / "dev-home"))
    assert result.code == 1, str(result)
    assert result.has_line(r"^PROBLEM\s+The dev-home folder .* is dev-home-tools' own"), str(result)
    assert read(settings) == before


def test_takes_only_its_own_options(box: Sandbox) -> None:
    result = setup(box, "--content")
    assert result.code == 1 and result.has_line(r"^PROBLEM\s+No such option: --content"), str(
        result
    )
    result = setup(box, "--content-dir")
    assert result.code == 1, str(result)
    assert result.has_line(r"^PROBLEM\s+--content-dir needs a folder after it"), str(result)
    result = run_python(box, "setup.py", "--help")
    assert result.code == 0 and result.has_line("--what-if"), str(result)


def test_what_if_changes_nothing(box: Sandbox) -> None:
    # Something for each kind of change: a link to make, a generated file to write, and a
    # dev-home folder to save, given here when the settings have none.
    link = box.profile / ".claude" / "skills" / "knowledge"
    template = box.tools / "templates" / "operating-rules" / "operating-rules.md"
    generated_rules = box.generated / "operating-rules" / "operating-rules.md"
    settings = box.tools / "local-settings.json"
    template_bytes, rules_bytes = template.read_bytes(), generated_rules.read_bytes()
    settings_bytes = settings.read_bytes()
    unset = json.loads(settings_bytes)
    unset["contentDir"] = ""
    write_text(settings, json.dumps(unset, indent=2) + "\n")
    unset_bytes = settings.read_bytes()
    remove_link(link)
    append(template, "- A line added to the operating rules.")
    try:
        result = run_python(box, "setup.py", "--what-if", "--content-dir", str(box.content))
        assert result.code == 0, str(result)
        assert result.has_line(r"^What if: Save this PC's settings: "), str(result)
        assert result.has_line(r"^What if: Create a link to "), str(result)
        assert result.has_line(r"^What if: Write a generated file: "), str(result)
        assert result.has_line("This was a preview"), str(result)
        assert link_target(link) is None
        assert generated_rules.read_bytes() == rules_bytes
        assert settings.read_bytes() == unset_bytes
    finally:
        settings.write_bytes(settings_bytes)
        template.write_bytes(template_bytes)
        setup(box)
    assert link_target(link) == box.generated / "skills" / "knowledge"


def test_what_if_with_no_dev_home_yet_says_the_rest_waits_for_it(box: Sandbox) -> None:
    missing = box.root / "no-dev-home-yet"
    result = run_python(box, "setup.py", "--what-if", "--content-dir", str(missing))
    assert result.has_line(r"^What if: the rest of setup works with dev-home"), str(result)
    assert not missing.exists()


def test_never_writes_through_a_link_above_a_generated_folder(box: Sandbox) -> None:
    skills = box.generated / "skills"
    outside = box.root / "someone-elses-folder"
    write_text(outside / "precious" / "keep.md", "keep\n")
    shutil.move(skills, box.root / "skills-aside")
    make_junction(skills, outside)
    try:
        result = setup(box)
        kept = sorted(path.name for path in outside.iterdir())
        skill_link = link_target(box.profile / ".claude" / "skills" / "handoff")
    finally:
        remove_link(skills)
        shutil.move(box.root / "skills-aside", skills)
    assert result.code == 1 and result.has_line(r"skills is a link, so setup left it alone"), str(
        result
    )
    assert kept == ["precious"], kept
    assert (outside / "precious" / "keep.md").is_file()
    # The skills are all still there, so their links stay.
    assert not result.has_line(r"^REMOVED\s"), str(result)
    assert skill_link == skills / "handoff"
    assert setup(box).code == 0


def test_reads_a_link_to_a_network_path_as_one(box: Sandbox) -> None:
    paths = shared_module(box, "paths")
    assert paths.without_long_prefix("\\\\?\\UNC\\server\\share\\x") == "\\\\server\\share\\x"
    assert paths.without_long_prefix("\\\\?\\C:\\x") == "C:\\x"


def test_an_empty_local_settings_file_holds_no_answers(
    box: Sandbox, monkeypatch: pytest.MonkeyPatch
) -> None:
    # Read here, not run: setup with no testHomeDir would set up the real profile.
    settings = shared_module(box, "settings")
    empty = box.root / "empty-settings.json"
    write_text(empty, "")
    monkeypatch.setattr(settings, "SETTINGS_PATH", empty)
    loaded = settings.load_local_settings()
    # It counts as no file, so the questions still come.
    assert loaded is not None and loaded.data == {} and loaded.content_dir == ""
    assert loaded.auto_update is None


# Settings changes, planned without writing anything.

ENTRIES = ["C:\\Users\\you\\dev-home", "C:\\Users\\you\\dev-home-tools"]
ROOT = "C:\\Users\\you\\dev-home"


def test_claude_settings_plans_a_new_file_with_both_folders(box: Sandbox) -> None:
    plan = shared_module(box, "claude_settings").plan(box.root / "plans" / "missing.json", ENTRIES)
    assert not plan.reason, plan.reason
    assert json.loads(plan.new_text)["permissions"]["additionalDirectories"] == ENTRIES


def test_claude_settings_adds_after_an_existing_entry_and_keeps_crlf(box: Sandbox) -> None:
    path = box.root / "plans" / "existing.json"
    path.parent.mkdir(exist_ok=True)
    text = '{\r\n  "permissions": {\r\n    "additionalDirectories": ["D:\\\\Other"]\r\n  }\r\n}\r\n'
    path.write_bytes(text.encode("utf-8"))
    plan = shared_module(box, "claude_settings").plan(path, ENTRIES)
    assert not plan.reason, plan.reason
    folders = json.loads(plan.new_text)["permissions"]["additionalDirectories"]
    assert folders == ["D:\\Other", *ENTRIES]
    assert "\r\n" in plan.new_text


@pytest.mark.parametrize(
    ("text", "reason"),
    [
        ('{"x": 1e5}\n', "1e5"),
        ('{"x": -0}\n', "-0"),
        ('{"x": NaN}\n', "not plain JSON"),
        ('{"x": 1, "x": 2}\n', "not plain JSON"),
    ],
    ids=["a number written another way", "minus zero", "NaN", "a key twice"],
)
def test_claude_settings_refuses_what_rewriting_would_change(
    box: Sandbox, text: str, reason: str
) -> None:
    path = box.root / "plans" / "numbers.json"
    path.parent.mkdir(exist_ok=True)
    path.write_bytes(text.encode("utf-8"))
    plan = shared_module(box, "claude_settings").plan(path, ENTRIES)
    assert plan.reason and reason in plan.reason, plan.reason


def test_claude_settings_keeps_plain_numbers(box: Sandbox) -> None:
    path = box.root / "plans" / "plain-numbers.json"
    path.parent.mkdir(exist_ok=True)
    path.write_bytes(b'{\n  "rate": 0.5,\n  "count": 12\n}\n')
    plan = shared_module(box, "claude_settings").plan(path, ENTRIES)
    assert not plan.reason, plan.reason
    assert '"rate": 0.5,' in plan.new_text and '"count": 12,' in plan.new_text


def test_claude_settings_refuses_a_file_with_comments(box: Sandbox) -> None:
    path = box.root / "plans" / "comments.json"
    path.parent.mkdir(exist_ok=True)
    path.write_bytes(b'{\n  // a comment\n  "model": "x"\n}\n')
    claude = shared_module(box, "claude_settings")
    assert claude.plan(path, ENTRIES).reason
    # Though the folders it allows can still be read from it.
    assert claude.folders_allowed(path.read_text()) == []


def test_codex_config_plans_both_settings_for_an_empty_file(box: Sandbox) -> None:
    path = box.root / "plans" / "empty.toml"
    path.parent.mkdir(exist_ok=True)
    path.write_bytes(b"")
    plan = shared_module(box, "codex_config").plan(path, ROOT, 65536)
    assert not plan.reason, plan.reason
    assert "writable_roots = ['C:\\Users\\you\\dev-home']" in plan.new_text
    assert "project_doc_max_bytes = 65536" in plan.new_text


def test_codex_config_adds_to_an_existing_writable_roots_list(box: Sandbox) -> None:
    path = box.root / "plans" / "other.toml"
    path.parent.mkdir(exist_ok=True)
    path.write_bytes(
        b"model = \"x\"\n\n[sandbox_workspace_write]\nwritable_roots = ['D:\\Other']\n"
    )
    plan = shared_module(box, "codex_config").plan(path, ROOT, 65536)
    assert not plan.reason, plan.reason
    assert "writable_roots = ['D:\\Other', 'C:\\Users\\you\\dev-home']" in plan.new_text


TABLE = "\n\n[sandbox_workspace_write]\nwritable_roots = "


@pytest.mark.parametrize(
    ("text", "configured"),
    [
        ("project_doc_max_bytes = 70000" + TABLE + '["C:/Users/you/dev-home"]\n', True),
        ("project_doc_max_bytes = 70000" + TABLE + "['C:\\Users\\you\\dev-home-tools']\n", False),
        ("project_doc_max_bytes = 32768" + TABLE + "['C:\\Users\\you\\dev-home']\n", False),
    ],
    ids=["a forward-slash path counts", "a longer path starting the same doesn't", "too few bytes"],
)
def test_codex_config_is_configured(box: Sandbox, text: str, configured: bool) -> None:
    assert shared_module(box, "codex_config").is_configured(text, ROOT, 65536) is configured


@pytest.mark.parametrize(
    ("text", "reason"),
    [
        ("project_doc_max_bytes.x = 1\n", "project_doc_max_bytes line is in a form"),
        ("[sandbox_workspace_write]\nwritable_roots.x = 1\n", "writable_roots line is in a form"),
        ('model = "x"\nmodel = "y"\n', "not valid TOML"),
    ],
    ids=["a dotted max bytes key", "a dotted writable_roots key", "a key set twice"],
)
def test_codex_config_refuses_what_it_cant_change_safely(
    box: Sandbox, text: str, reason: str
) -> None:
    path = box.root / "plans" / "refused.toml"
    path.parent.mkdir(exist_ok=True)
    path.write_bytes(text.encode("utf-8"))
    plan = shared_module(box, "codex_config").plan(path, ROOT, 65536)
    assert plan.reason and reason in plan.reason, plan.reason


def test_codex_config_keeps_everything_else_as_toml_reads_it(box: Sandbox) -> None:
    codex = shared_module(box, "codex_config")
    old = (
        '# mine\nmodel = "x"\nproject_doc_max_bytes = 1_000\n\n[sandbox_workspace_write]\n'
        "network_access = true\nwritable_roots = [\n  'D:\\Other', # a comment\n]\n"
    )
    path = box.root / "plans" / "kept.toml"
    path.parent.mkdir(exist_ok=True)
    path.write_bytes(old.encode("utf-8"))
    plan = codex.plan(path, ROOT, 65536)
    assert not plan.reason, plan.reason
    assert codex.same_apart_from_change(old, plan.new_text, ROOT, 65536)
    # And the check catches a change to anything else.
    other = plan.new_text.replace("network_access = true", "network_access = false")
    assert not codex.same_apart_from_change(old, other, ROOT, 65536)


def test_claude_settings_refuses_half_a_character(box: Sandbox) -> None:
    path = box.root / "plans" / "surrogate.json"
    path.parent.mkdir(exist_ok=True)
    path.write_bytes(b'{"x": "\\ud800"}\n')
    plan = shared_module(box, "claude_settings").plan(path, ENTRIES)
    assert plan.reason and "unpaired surrogate" in plan.reason, plan.reason


def test_a_read_only_settings_file_is_never_planned_or_written(box: Sandbox) -> None:
    path = box.root / "plans" / "read-only.json"
    path.parent.mkdir(exist_ok=True)
    path.write_bytes(b"{}\n")
    path.chmod(stat.S_IREAD)
    try:
        plan = shared_module(box, "claude_settings").plan(path, ENTRIES)
        with pytest.raises(PermissionError):
            shared_module(box, "settings_files").write_settings_file(
                path, "[]\n", bom=False, backup=True
            )
        left = sorted(entry.name for entry in path.parent.glob("read-only.json*"))
    finally:
        path.chmod(stat.S_IREAD | stat.S_IWRITE)
    assert plan.reason == "it is read-only", plan.reason
    assert path.read_bytes() == b"{}\n"
    assert left == ["read-only.json"], "no backup and no new file left beside it"


def test_a_settings_file_held_open_for_a_moment_is_still_replaced(box: Sandbox) -> None:
    # Windows refuses to replace a file another program has open, as antivirus may for a moment.
    path = box.root / "plans" / "held.json"
    path.parent.mkdir(exist_ok=True)
    path.write_bytes(b"{}\n")
    held = path.open("rb")
    timer = threading.Timer(0.3, held.close)
    started = time.monotonic()
    timer.start()
    try:
        backup = shared_module(box, "settings_files").write_settings_file(
            path, "[]\n", bom=False, backup=True
        )
    finally:
        timer.cancel()
        held.close()
    waited = time.monotonic() - started
    assert path.read_bytes() == b"[]\n"
    assert Path(backup).read_bytes() == b"{}\n"
    Path(backup).unlink()
    if sys.platform == "win32":
        assert waited >= 0.3, "it waited for the file to be closed, rather than failing"


@pytest.mark.skipif(sys.platform != "win32", reason="only Windows refuses to replace an open file")
def test_a_settings_file_held_open_too_long_is_left_as_it_was(
    box: Sandbox, monkeypatch: pytest.MonkeyPatch
) -> None:
    settings_files = shared_module(box, "settings_files")
    monkeypatch.setattr(settings_files, "REPLACE_WAIT_SECONDS", 0.3)
    path = box.root / "plans" / "held-long.json"
    path.parent.mkdir(exist_ok=True)
    path.write_bytes(b"{}\n")
    with path.open("rb"), pytest.raises(PermissionError):
        settings_files.write_settings_file(path, "[]\n", bom=False, backup=True)
    assert path.read_bytes() == b"{}\n"
    left = sorted(entry.name for entry in path.parent.glob("held-long.json*"))
    assert left == ["held-long.json"], "no backup and no new file left beside it"


def test_a_settings_file_saved_without_a_backup_gets_none(box: Sandbox) -> None:
    path = box.root / "plans" / "no-backup.json"
    path.parent.mkdir(exist_ok=True)
    path.write_bytes(b"{}\n")
    written = shared_module(box, "settings_files").write_settings_file(
        path, "[]\n", bom=False, backup=False
    )
    assert written == ""
    assert path.read_bytes() == b"[]\n"
    left = sorted(entry.name for entry in path.parent.glob("no-backup.json*"))
    assert left == ["no-backup.json"], "no backup and no new file left beside it"
